### ISSUE TITLE
SES.pd

### ISSUE THREAD

**Issue by MovieBuff77** [gabferreira/phyloraster#6]
I tried to run an example of SES code that was feasible. But when I run large data SES, it always goes wrong. null.pd <-rast.pd.ses(data$x, tree, aleats = 3, random = "spat",overwrite=TRUE)
错误: [writeStart] file exists. You can use 'overwrite=TRUE' to overwrite i但是执行overwrite=TRUE后依然显示错误: [writeStart] file exists. You can use 'overwrite=TRUE' to overwrite

**Comment by ZMgogo** [comment]
I also met this issue.

**Comment by MovieBuff77** [comment]
文件已收到  ，谢谢                         LB

**Comment by gabferreira** [comment]
Hello, thank you for reporting this. This error was due to an issue in version 0.7.0 of SESraster, a dependency used to calculate null models, and was resolved with version 0.7.1 of the SESraster package. The new version of the SESraster package will soon be available on CRAN, but for now we invite you to install it using devtools.
require(devtools)
install_github("HemingNM/SESraster", build_vignettes = TRUE)
